language: android
jdk:
  - oraclejdk8
git:
  submodules: false
sudo: required
#dist: trusty
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - cmake
    - g++-6
android:
  components:
    - tools
    - tools
    - platform-tools
    - build-tools-24.0.3
    - android-24
    - extra-android-m2repository
before_install:
    - sed -i 's/git@github.com:/https:\/\/github.com\//' .gitmodules
    - git submodule update --init --recursive
install:
# Android NDK
    #- if [ `uname -m` = x86_64]; then wget http://dl.google.com/android/ndk/android-ndk-r9c-linux-x86_64.tar.bz2 -O ndk.tgz; else wget http://dl.google.com/android/ndk/android-ndk-r9c-linux-x86.tar.bz2 -O ndk.tgz; fi
    #- tar -xf ndk.tgz
    - wget https://dl.google.com/android/repository/android-ndk-r13-linux-x86_64.zip -O ndk.zip
    - unzip -qq ndk.zip
    - export ANDROID_NDK_HOME=`pwd`/android-ndk-r13
    - export PATH=${PATH}:${ANDROID_HOME}/tools:${ANDROID_HOME}/platform-tools:${ANDROID_NDK_HOME}
# CMake for Android NDK
    - wget https://github.com/Commit451/android-cmake-installer/releases/download/1.1.0/install-cmake.sh
    - chmod +x install-cmake.sh
    - ./install-cmake.sh
before_script:
 # - export CXX=$COMPILER
    - unlink /usr/bin/g++
    - ln -s /usr/bin/g++-6 /usr/bin/g++
    - export CMAKE_EXECUTABLE=`find ${ANDROID_HOME}cmake/*/bin/cmake`
    - mkdir native-build
    - cd native-build
    - ${CMAKE_EXECUTABLE} -DPLATFORM:STRING=pc ../app/
    - cd ..
script:
    - ./gradlew build
# Server build
    - cd native-build
    - ${CMAKE_EXECUTABLE} --build .
