version: 1.0.{build}

skip_tags: true

os:
  - Visual Studio 2015

build:
  parallel: true
  verbosity: minimal
  
install:
  - cmd: copy .gitmodules .gitmodules_old /y
  - ps: get-content .gitmodules_old | %{$_ -replace "git@github.com:","https://github.com/"} | set-content .gitmodules
  - ps: cat .gitmodules
  - cmd: git submodule update --init --recursive

init:
  - cmd: cmake --version

before_build:
  - cmd: mkdir build
  - cmd: cd build
  - cmd: cmake -DPLATFORM:STRING=pc ../app/
  - cmd: cd ../

deploy: off
